{% set name = "nbprint" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df2e6d289be3a8f2e5f27d52c0afdd3d8bb31db1a64574eea915139072ab7016

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.8
    - dominate
    - ipywidgets
    - ipython
    - nbformat
    - notebook
    - omegaconf
    - pydantic

test:
  imports:
    - nbprint

about:
  home: http://github.com/timkpaine/nbprint
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building Jupyter reports with NBConvert
  description: A framework for building Jupyter reports with NBConvert
  dev_url: https://github.com/timkpaine/nbprint

extra:
  recipe-maintainers:
    - timkpaine
