{% set name = "nbprint" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9bf3be51f703efc73630161b1e73ae0d680e99fdd6a1763aeb730564d63f67dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.8
    - dominate
    - ipywidgets
    - ipython
    - nbconvert
    - nbformat
    - notebook
    - omegaconf
    - pydantic >=2,<3
    - pydantic-extra-types
    - typer

test:
  imports:
    - nbprint
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/timkpaine/nbprint
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building Jupyter reports with NBConvert
  description: A framework for building Jupyter reports with NBConvert
  dev_url: https://github.com/timkpaine/nbprint

extra:
  recipe-maintainers:
    - timkpaine
